### ISSUE TITLE
Not working on MacOS sandbox mode

### ISSUE THREAD

**Issue by vadimbarda** [pcpl2/flutterMediainfo#8]
Hi. I try to use this awesome package on Mac and have issue `Invalid argument(s): Failed to load dynamic library 'libmediainfo.0.dylib': dlopen(libmediainfo.0.dylib, 0x0001): tried: '/Users/<user>/Dev/projects/<app_name>/build/macos/Build/Products/Debug/<app_name>.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/./libmediainfo.0.dylib' (no such file),`

I think this issue is happens exactly in sandbox mode. I also have issue on Windows with this library in sandbox mode after pack to msix and install. But I've found workaround. Exactly one library MediaInfo.dll need to copy to VFS/SystemX64/ folder before packing. And after that it can find dynamic library. Maybe there is also similar workaround on Mac, but I will be thankful if this issue will be fixed 

Flutter (Channel beta, 3.4.0-17.2.pre, on macOS 12.5 21G72 darwin-x64, locale en-UA)
Xcode - develop for iOS and macOS (Xcode 13.4.1)
MacOS Monterey 12.6.2

I hope issue in the way how dynamic library included. I think it should be something like https://github.com/alexmercerind/dart_vlc/blob/master/lib/dart_vlc.dart#L114

**Comment by pcpl2** [comment]
Hi, I fixed this problem for macOS system on the dev branch, but I want to release a new version only after testing these changes on all supported platforms.

**Comment by vadimbarda** [comment]
> Hi, I fixed this problem for macOS system, but I want to release a new version only after testing these changes on all supported platforms.

Any updates? Do you have any plans for that? Are you going to do that in few days or weeks?

**Comment by pcpl2** [comment]
I think I'll release versions after the weekend.

**Comment by pcpl2** [comment]
I released version 0.0.3 which fixes this bug and has some minor improvements.
